# site settings
title: Agenda transparencia
email: prensa@ciudadanointeligente.org
description: Estos son los 15 puntos clave del Informe Anticorrupción según Ciudadano Inteligente. ¡Difunde!
baseurl: '//beta.agendatransparencia.cl' #example: '/agendatransparencia'
basedomain: beta.agendatransparencia.cl #ciudadanointeligente.github.io
analytics: 'UA-41822715-6'

# social
hashtag: AgendaTransparencia
twitter_username: ciudadanoi
twitter_txt: 'Estos son los 15 puntos clave del Informe Anticorrupción según @ciudadanoi. Difunde en'

# build settings
markdown: kramdown

collections:
  cards:
    output: true
