# site settings
title: Agenda transparencia
email: info@ciudadanointeligente.org
description: Dale seguimiento a las propuestas del Consejo Anticorrupción.
baseurl: '/agendatransparencia' #example: 'http://agendatransparencia.cl'
basedomain: ciudadanointeligente.github.io #agendatransparencia.cl
#analytics: 'UA-XXXXXXXX-X'

#social
hashtag: CadenaNacional
twitter_username: ciudadanoi
twitter_txt: 'Estos son los 15 puntos claves del Informe Anticorrupción según @ciudadanoi. Difunde en'

# build settings
markdown: kramdown

collections:
  campaign_flyers:
    output: true