# site settings
title: Agenda transparencia
email: info@ciudadanointeligente.org
description: Estos son los 15 puntos clave del Informe Anticorrupción según Ciudadano Inteligente. ¡Difunde!
baseurl: '//agendatransparencia.cl' #example: '/agendatransparencia'
basedomain: agendatransparencia.cl #ciudadanointeligente.github.io
analytics: 'UA-41822715-6'

# social
hashtag: AgendaTransparencia
twitter_username: ciudadanoi
twitter_txt: 'Estos son los 15 puntos clave del Informe Anticorrupción según @ciudadanoi. Difunde en'

# build settings
markdown: kramdown

collections:
  cards:
    output: true